### ISSUE TITLE
[Filtering] product category dropdown menu

### ISSUE THREAD

**Issue by kerstinopen** [loefel/opensourcedesign#20]
In the filtering section it would be useful to have a dropdown menu for the different product categories.

**Comment by jbon** [comment]
I suggest using the level 1 of the google product taxonomy: https://www.google.com/basepages/producttype/taxonomy.en-US.txt

(contains 20 categories)

It is quit unprecise but i don't think we need more precision than this anyway since we have another field precising the type of products (field "product description")

**Comment by jbon** [comment]
The description of the field on the edition page should consequently be: 

> Product category: Classification of the product according to the Google Product Taxonomy (as defined [here](https://www.google.com/basepages/producttype/taxonomy.en-US.txt)).

**Comment by jbon** [comment]
This will require erasing all data in the field "product category" and reallocate each product manually to a new category.
